@tag
Feature: Batch Functions
  Different Batch functions performed by Admin
  
  Background: Admin is logged in and programs were created

  @tag1
  Scenario: Check whether admin is able to see all existing batches details
  Given Admin is on Manage Batches Page(admin) screen, by clicking on batches tab
  When Admin tries to view exisiting Batch details
  Then All the existing Batch details details will be displayed in Manage Batches Page(Admin)
  
  @tag2
  Scenario: Check whether admin can add batch to batches list
  Given Admin is on Add tab of ADD/Edit batches page (admin) by clicking on Add Batch in Manage Batches Page(admin) 
  When Admin clicks on submit button after entering Batch Name, Batch Description,select Batch Status, enters BatchNo. of classes.
  Then Created Batch details will be displayed in Manage Batches Page(Admin) with auto generated Created Date and Modified date in MM/DD/YY format.
  
  @tag3
  Scenario: Check whether admin can edit particular batch in batches list
  Given Admin is on Edit tab of ADD/Edit batches page (admin) by clicking on edit icon
  When Admin clicks on submit button after updating Batch Name, Batch Description,select Batch Status, Baych No. of classes
  Then Updated Batch details will be displayed in Manage Batches Page(Admin) screen with same autogenerated creation date and  different Modified date in MM/DD/YY format
  
  @tage4
  Scenario: Check whether admin can delete particular batch from batches list
  Given Admin is on Manage Batches Page(admin) screen
  When Admin clicks on particular batch trash icon
  Then Batch will be deleted from the Batches List in Manage Batches Page(admin)
  
   
